### ISSUE TITLE
Serial terminal window does not fit the viewport

### ISSUE THREAD

**Issue by MartinUbl** [silhavyj/ZeroMate#118]
🐞 **Bug description**
When running ZeroMate on Windows (probably affects other OS's, but it was observed on Windows), the UART terminal does not fit the viewport and introduces a scollbar to reach the bottom of the widget. As the input field for sending text to the emulated machine is attached to the bottom, it is not visible by default and confuses users.

🔍 **How to reproduce the bug**
1. Configure ZeroMate on Windows with UART terminal enabled
2. Display the serial terminal window, make it dock on the side together with other components, so it displays a scrollbar
3. See the error

🤔 **What is the expected behavior**
The input field and "Send" button should display at the bottom of the widget inside the viewport, and the scrollbar should apply to the output area only.

📎 **Attachments**
Screenshot of serial terminal widget with out-of-viewport input fields.

🖥️ **What OS do you use?**
Windows 10, Windows 11

🔧 **What compiler was used to build the application?**
Not applicable - the latest release version from GitHub was used.

📝 **Anything else?**
Not applicable.

![screen](https://github.com/silhavyj/ZeroMate/assets/107725/1394de88-eede-425d-b6cb-90cb242af6ab)

**Comment by silhavyj** [comment]
I can see why it might be kinda confusing. It's due to the fixed height of the output window itself - it's implemented as an array of 80x25 characters. Would moving the user input up to the top, as shown in the attachment, help? It's probably the easiest & quickest solution I can think of at the moment.

![screenshot_01](https://github.com/silhavyj/ZeroMate/assets/64095079/17983e8c-d489-460d-b164-e97058c22720)

**Comment by MartinUbl** [comment]
I would consider it a good compromise solution. Thanks.
